### ISSUE TITLE
Where can I get MusiSyncForCalao.ttf?

### ISSUE THREAD

**Issue by Smibu** [Neonunux/calao#34]
I managed to build and run this project, but it turns out the program requires the file `MusiSyncForCalao.ttf` which does not seem to exist in the repository and it's also been added in `.gitignore`. Where can I get this file, or is there a workaround? Are any other files needed to run the program? I see a few other related entries in `.gitignore`.

**Comment by Neonunux** [comment]
Sorry fort this buggy version in master branch.
I'll get it back when i Come back from holiday on saturday (no computer furthermore)

**Comment by theobat** [comment]
Hey @Neonunux, I get the same sort of bug : 
```23:04:07.439 [main] ERROR calao.Calao - Cannot load MusiSync font !!```
Any idea on this ?

**Comment by Neonunux** [comment]
b8818a292bae2cc36a02e39999afac4bd0575310
